### ISSUE TITLE
loaderClass attribute is not working

### ISSUE THREAD

**Issue by hem19** [moff/angular2-loaders-css#1]
I have given the loaderClass attribute in component.html file like this:
`<loaders-css [loader]="'square-spin'" [loaderClass]="'spinner'"></loaders-css>`
and defined the spinner class in component.css file like this:

```
.spinner {
background: black;
background-color: black;
}
```

But still background colors and other properties are not applying on the loader.

Can you check the same and let me know if I am doing anything wrong.

**Comment by moff** [comment]
Hi @hem19!

You have to update your CSS to this:

```
.loader .spinner {
    background: black;
    background-color: black;
}
```

Thanks for spotting this issue - I've updated `README.md`!

**Comment by hem19** [comment]
Hi @moff 
I tried with your provided solution but it is not working as well.
I have to write following code in component css to make it work:

```
:host /deep/ .spinner {
    background-color: black;
}
```

**Comment by moff** [comment]
@hem19 can you please provide a link to repo with code reproducing this issue?

**Comment by pantonis** [comment]
@moff Have the same problem. I add this to my style.css

```
.loader .my-loader {
    background-color: #217ebd!important;
}
```
But nothing changes

**Comment by moff** [comment]
@pantonis , @hem19 I've just tested it locally and it worked perfectly. I'm using Angular CLI. This is a merely a CSS issue that can happen for some reason. I'd be grateful, if you create a repo at GitHub that reproduces this error.

**Comment by pantonis** [comment]
@moff where do I have to add this

```
.loader .my-loader {
    background-color: #217ebd!important;
}
```

**Comment by moff** [comment]
@pantonis just add this to your `styles.css` or whatever css-file you have there that goes after loaders css-file.

**Comment by pantonis** [comment]
Yes I added this yesterday and I can verify it works. I forgot to add styles.css on angular-cli.json :) sorry.

**Comment by moff** [comment]
@pantonis, @hem19 thank you for a feedback!
