### ISSUE TITLE
Can't perform an AoT build.

### ISSUE THREAD

**Issue by MrTimms** [moff/angular2-loaders-css#2]
Hi, I'm trying to perform an AoT build but I receive this error:

            </div>
              <div>
                  <loaders-css *ngIf="loading" [ERROR ->][loader]="'ball-triangle-path'" [loaderClass]="'my-loader'"></loaders-css>
                  <table "): MyComponent@10:47
Can't bind to 'loaderClass' since it isn't a known property of 'loaders-css'.
1. If 'loaders-css' is an Angular component and it has 'loaderClass' input, then verify that it is part of this module.
2. If 'loaders-css' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 

              <div>
                  <loaders-css *ngIf="loading" [loader]="'ball-triangle-path'" [ERROR ->][loaderClass]="'my-loader'"></loaders-css>
                  <table class="ocs-table">
            "): MyComponent@10:79
'loaders-css' is not a known element:
1. If 'loaders-css' is an Angular component, then verify that it is part of this module.
2. If 'loaders-css' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. 

I'm using the Angular-CLI 1.0.0-beta.22-1 using the command _ng build --aot_.

Please let me know if you need more info.

**Comment by MrTimms** [comment]
@moff Any update?

**Comment by moff** [comment]
@MrTimms Sorry for the delay. At the moment I'm traveling so I don't have time and opportunity to fix this issue. I'll take a look when I'll get back home. Sorry for that!

**Comment by pantonis** [comment]
@MrTimms  same problem here did you manage to resolve it?

**Comment by moff** [comment]
@MrTimms what package version do you use?

**Comment by MrTimms** [comment]
I never got it working so I moved on to a different package.

**Comment by pantonis** [comment]
@MrTimms which package?
@moff I am using "angular2-loaders-css": "1.0.7", with angular 4

**Comment by moff** [comment]
@MrTimms, @pantonis this package will be fixed at the beginning of next week - I've got other packages that had same issue, so it's just a matter of free time. Thanks for a feedback!

**Comment by moff** [comment]
@MrTimms , @pantonis I've just updated the package - tested with Angular-CLI and AoT - it should work fine by now. Check it out and let me know that it works properly on your side.

**Comment by pantonis** [comment]
@moff Can verify that this is working! Thanks

**Comment by moff** [comment]
@pantonis Thanks for a feedback!
