### ISSUE TITLE
LoadersCssModule is not an NgModule

### ISSUE THREAD

**Issue by tsironis13** [moff/angular2-loaders-css#3]
i am getting the feautured log message when trying to import the module...

**Comment by rightisleft** [comment]
I'm getting the same error when running the angular-cli


➜  web git:(master) ✗ ng --version
angular-cli: 1.0.0-beta.26
node: 6.9.1
os: darwin x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.3.1
@angular/compiler-cli: 2.4.4

ng serve ... 
ERROR in LoadersCssModule is not an NgModule

**Comment by rightisleft** [comment]
@moff - any idea when you'll be able to look at this? This started when i upgraded from angular-cli beta 22 to 26

**Comment by rightisleft** [comment]
This might just be a publishing issue. When i copy your module / component file and load them as part of my project - they behave correctly.

**Comment by ssi-hu-tasi-norbert** [comment]
workaround:
import {LoadersCssModule} from "angular2-loaders-css/module/module";

**Comment by moff** [comment]
@tsironis13 , @rightisleft , @ssi-hu-tasi-norbert I've just updated the package - tested with Angular-CLI and AoT - it should work fine by now. Check it out and let me know that it works properly on your side.

**Comment by ssi-hu-tasi-norbert** [comment]
It works.

Thanks
